// Test data of the map canvas: minimal basemaps, a few layers of each of the two OpenFreeMap styles the map uses,
// copied as they are (downloaded on 2026-09-24), so the layers of the app are checked against real neighbours: the
// ground and the buildings under the grid, the roads over it, the labels and their expressions.
//   https://tiles.openfreemap.org/styles/positron — OpenFreeMap fork of openmaptiles/positron-gl-style
//   https://tiles.openfreemap.org/styles/dark — OpenFreeMap fork of openmaptiles/dark-matter-gl-style
// Licence of the styles: code BSD-3-Clause, design CC BY 4.0 (OpenMapTiles; Positron and Dark Matter derive from the
// CARTO basemaps by Stamen and Paul Norman, CC BY 3.0); OpenFreeMap styles repository — MIT. Only in tests.

export const positronFixture = {
  "version": 8,
  "sources": {"openmaptiles": {"type": "vector", "url": "https://tiles.openfreemap.org/planet"}},
  "sprite": "https://tiles.openfreemap.org/sprites/ofm_f384/ofm",
  "glyphs": "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  "layers": [
    {"id": "background", "type": "background", "paint": {"background-color": "rgb(242,243,240)"}},
    {"id": "water", "type": "fill", "source": "openmaptiles", "source-layer": "water", "filter": ["all", ["match", ["geometry-type"], ["MultiPolygon", "Polygon"], true, false], ["!=", ["get", "brunnel"], "tunnel"]], "paint": {"fill-antialias": true, "fill-color": "rgb(194, 200, 202)"}},
    {"id": "landuse_residential", "type": "fill", "source": "openmaptiles", "source-layer": "landuse", "maxzoom": 16, "filter": ["all", ["match", ["geometry-type"], ["MultiPolygon", "Polygon"], true, false], ["==", ["get", "class"], "residential"]], "paint": {"fill-color": "rgb(234, 234, 230)", "fill-opacity": ["interpolate", ["exponential", 0.6], ["zoom"], 8, 0.8, 9, 0.6]}},
    {"id": "building", "type": "fill", "source": "openmaptiles", "source-layer": "building", "minzoom": 12, "paint": {"fill-antialias": true, "fill-color": "rgb(234, 234, 229)", "fill-outline-color": "rgb(219, 219, 218)"}},
    {"id": "highway_minor", "type": "line", "source": "openmaptiles", "source-layer": "transportation", "minzoom": 8, "filter": ["all", ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], ["match", ["get", "class"], ["minor", "service", "track"], true, false]], "layout": {"line-cap": "round", "line-join": "round"}, "paint": {"line-color": "hsl(0,0%,88%)", "line-opacity": 0.9, "line-width": ["interpolate", ["exponential", 1.55], ["zoom"], 13, 1.8, 20, 20]}},
    {"id": "boundary_3", "type": "line", "source": "openmaptiles", "source-layer": "boundary", "minzoom": 8, "filter": ["all", [">=", ["get", "admin_level"], 3], ["<=", ["get", "admin_level"], 6], ["!=", ["get", "maritime"], 1], ["!=", ["get", "disputed"], 1], ["!", ["has", "claimed_by"]]], "paint": {"line-color": "hsl(0,0%,70%)", "line-dasharray": [1, 1], "line-width": ["interpolate", ["linear", 1], ["zoom"], 7, 1, 11, 2]}},
    {"id": "waterway_line_label", "type": "symbol", "source": "openmaptiles", "source-layer": "waterway", "minzoom": 10, "filter": ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], "layout": {"symbol-placement": "line", "symbol-spacing": 350, "text-field": ["case", ["has", "name:nonlatin"], ["concat", ["get", "name:latin"], " ", ["get", "name:nonlatin"]], ["coalesce", ["get", "name_en"], ["get", "name"]]], "text-font": ["Noto Sans Italic"], "text-letter-spacing": 0.2, "text-max-width": 5, "text-size": 14}, "paint": {"text-color": "hsl(0,0%,66%)", "text-halo-color": "rgba(255,255,255,0.7)", "text-halo-width": 1.5}},
    {"id": "highway-name-minor", "type": "symbol", "source": "openmaptiles", "source-layer": "transportation_name", "minzoom": 15, "filter": ["all", ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], ["match", ["get", "class"], ["minor", "service", "track"], true, false]], "layout": {"symbol-placement": "line", "text-field": ["case", ["has", "name:nonlatin"], ["concat", ["get", "name:latin"], " ", ["get", "name:nonlatin"]], ["coalesce", ["get", "name_en"], ["get", "name"]]], "text-font": ["Noto Sans Regular"], "text-rotation-alignment": "map", "text-size": ["interpolate", ["linear"], ["zoom"], 13, 12, 14, 13]}, "paint": {"text-color": "#666", "text-halo-blur": 0.5, "text-halo-width": 1}},
    {"id": "highway-shield-non-us", "type": "symbol", "source": "openmaptiles", "source-layer": "transportation_name", "minzoom": 11, "filter": ["all", ["<=", ["get", "ref_length"], 6], ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], ["match", ["get", "network"], ["us-highway", "us-interstate", "us-state"], false, true]], "layout": {"icon-image": ["concat", "road_", ["get", "ref_length"]], "icon-rotation-alignment": "viewport", "icon-size": 1, "symbol-placement": ["step", ["zoom"], "point", 11, "line"], "symbol-spacing": 200, "text-field": ["to-string", ["get", "ref"]], "text-font": ["Noto Sans Regular"], "text-rotation-alignment": "viewport", "text-size": 10}},
    {"id": "label_city", "type": "symbol", "source": "openmaptiles", "source-layer": "place", "minzoom": 3, "filter": ["all", ["==", ["get", "class"], "city"], ["!=", ["get", "capital"], 2]], "layout": {"icon-allow-overlap": true, "icon-image": ["step", ["zoom"], "circle_11_black", 9, ""], "icon-optional": false, "icon-size": 0.4, "text-anchor": "bottom", "text-field": ["case", ["has", "name:nonlatin"], ["concat", ["get", "name:latin"], "\n", ["get", "name:nonlatin"]], ["coalesce", ["get", "name_en"], ["get", "name"]]], "text-font": ["Noto Sans Regular"], "text-max-width": 8, "text-offset": [0, -0.1], "text-size": ["interpolate", ["exponential", 1.2], ["zoom"], 4, 11, 7, 13, 11, 18]}, "paint": {"text-color": "#000", "text-halo-blur": 1, "text-halo-color": "#fff", "text-halo-width": 1}},
  ],
};

export const darkFixture = {
  "version": 8,
  "sources": {"openmaptiles": {"type": "vector", "url": "https://tiles.openfreemap.org/planet"}},
  "sprite": "https://tiles.openfreemap.org/sprites/ofm_f384/ofm",
  "glyphs": "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  "layers": [
    {"id": "background", "type": "background", "paint": {"background-color": "rgb(12,12,12)"}},
    {"id": "water", "type": "fill", "source": "openmaptiles", "source-layer": "water", "filter": ["all", ["match", ["geometry-type"], ["MultiPolygon", "Polygon"], true, false], ["!=", ["get", "brunnel"], "tunnel"]], "paint": {"fill-antialias": false, "fill-color": "rgb(27 ,27 ,29)"}},
    {"id": "water_name", "type": "symbol", "source": "openmaptiles", "source-layer": "water_name", "filter": ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], "layout": {"symbol-placement": "line", "symbol-spacing": 500, "text-field": ["case", ["has", "name:nonlatin"], ["concat", ["get", "name:latin"], "\n", ["get", "name:nonlatin"]], ["coalesce", ["get", "name_en"], ["get", "name"]]], "text-font": ["Noto Sans Regular"], "text-rotation-alignment": "map", "text-size": 12}, "paint": {"text-color": "hsla(0,0%,0%,0.7)", "text-halo-color": "hsl(0,0%,27%)"}},
    {"id": "building", "type": "fill", "source": "openmaptiles", "source-layer": "building", "minzoom": 12, "filter": ["match", ["geometry-type"], ["MultiPolygon", "Polygon"], true, false], "paint": {"fill-antialias": true, "fill-color": "rgb(10,10,10)", "fill-outline-color": "rgb(27 ,27 ,29)"}},
    {"id": "highway_minor", "type": "line", "source": "openmaptiles", "source-layer": "transportation", "minzoom": 8, "filter": ["all", ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], ["match", ["get", "class"], ["minor", "service", "track"], true, false]], "layout": {"line-cap": "round", "line-join": "round"}, "paint": {"line-color": "#181818", "line-opacity": 0.9, "line-width": ["interpolate", ["exponential", 1.55], ["zoom"], 13, 1.8, 20, 20]}},
    {"id": "road_oneway", "type": "symbol", "source": "openmaptiles", "source-layer": "transportation", "minzoom": 15, "filter": ["==", ["get", "oneway"], 1], "layout": {"icon-image": "oneway", "icon-padding": 2, "icon-rotate": 0, "icon-rotation-alignment": "map", "icon-size": ["interpolate", ["linear"], ["zoom"], 15, 0.5, 19, 1], "symbol-placement": "line", "symbol-spacing": 200}, "paint": {"icon-opacity": 0.5}},
    {"id": "highway_name_other", "type": "symbol", "source": "openmaptiles", "source-layer": "transportation_name", "filter": ["all", ["!=", ["get", "class"], "motorway"], ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false]], "layout": {"symbol-placement": "line", "symbol-spacing": 350, "text-field": ["case", ["has", "name:nonlatin"], ["concat", ["get", "name:latin"], " ", ["get", "name:nonlatin"]], ["coalesce", ["get", "name_en"], ["get", "name"]]], "text-font": ["Noto Sans Regular"], "text-max-angle": 30, "text-pitch-alignment": "viewport", "text-rotation-alignment": "map", "text-size": 10, "text-transform": "uppercase"}, "paint": {"text-color": "rgba(80, 78, 78, 1)", "text-halo-blur": 0, "text-halo-color": "rgba(0, 0, 0, 1)", "text-halo-width": 1, "text-translate": [0, 0]}},
    {"id": "highway_name_motorway", "type": "symbol", "source": "openmaptiles", "source-layer": "transportation_name", "filter": ["all", ["match", ["geometry-type"], ["LineString", "MultiLineString"], true, false], ["==", ["get", "class"], "motorway"]], "layout": {"symbol-placement": "line", "symbol-spacing": 350, "text-field": ["to-string", ["get", "ref"]], "text-font": ["Noto Sans Regular"], "text-pitch-alignment": "viewport", "text-rotation-alignment": "viewport", "text-size": 10}, "paint": {"text-color": "hsl(0,0%,37%)", "text-translate": [0, 2]}},
    {"id": "boundary_state", "type": "line", "source": "openmaptiles", "source-layer": "boundary", "filter": ["==", ["get", "admin_level"], 4], "layout": {"line-cap": "round", "line-join": "round"}, "paint": {"line-blur": 0.4, "line-color": "hsl(0,0%,21%)", "line-dasharray": [2, 2], "line-opacity": 1, "line-width": ["interpolate", ["exponential", 1.3], ["zoom"], 3, 1, 22, 15]}},
    {"id": "place_city", "type": "symbol", "source": "openmaptiles", "source-layer": "place", "maxzoom": 14, "filter": ["all", ["match", ["geometry-type"], ["MultiPoint", "Point"], true, false], ["==", ["get", "class"], "city"], [">", ["get", "rank"], 3]], "layout": {"icon-image": ["step", ["zoom"], "circle-11", 9, ""], "icon-size": 0.4, "text-anchor": ["step", ["zoom"], "left", 8, "center"], "text-field": ["case", ["has", "name:nonlatin"], ["concat", ["get", "name:latin"], "\n", ["get", "name:nonlatin"]], ["coalesce", ["get", "name_en"], ["get", "name"]]], "text-font": ["Noto Sans Regular"], "text-justify": "left", "text-offset": [0.5, 0.2], "text-size": 10, "text-transform": "uppercase"}, "paint": {"icon-opacity": 0.7, "text-color": "rgb(101,101,101)", "text-halo-blur": 1, "text-halo-color": "rgba(0,0,0,0.7)", "text-halo-width": 1}},
  ],
};
