import { stringify } from 'yaml';
import { fixedClock } from '../shell/clock.js';
import { buildServer } from '../shell/http/server.js';
import type { RouteService } from '../shell/services/routes.js';

export const OPENAPI_HEADER = '# Generated by `pnpm --filter @otkryvay/api openapi` — do not edit by hand.\n';

const unused = () => {
  throw new Error('not called while generating the spec');
};

/** Builds the server with stub dependencies and returns the OpenAPI document as YAML. */
export async function buildOpenApiYaml(): Promise<string> {
  const app = await buildServer({
    checkDb: async () => {},
    webhook: { secret: 'spec-only', handleUpdate: async () => {} },
    api: {
      routes: new Proxy({}, { get: () => unused }) as RouteService,
      recordEvent: async () => {},
      clock: fixedClock('2026-01-01T00:00:00Z'),
      auth: { botToken: undefined, maxAgeSeconds: 0, devBypass: false },
    },
  });
  await app.ready();
  // As app.swagger({ yaml: true }) writes it ({ strict: false }), but quoted where a YAML 1.1 parser (PyYAML,
  // SnakeYAML…) would read something else: a bare off or n is a boolean there.
  const yaml = stringify(app.swagger(), { strict: false, compat: 'yaml-1.1' });
  await app.close();
  return OPENAPI_HEADER + yaml;
}
